#!/usr/bin/env bash
# a Bash script that will display information about subdomains
# shellcheck disable=SC2086

dig_url () {
rec_ip="$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline; print $4, $5}')"
read -ra values <<< "$rec_ip"
echo "A subdomain $2 is a ${values[0]} record and points at ${values[1]}"
}

[[ $# -eq 2 ]] && dig_url "$1" "$2"
[[ $# -eq 1 ]] && (
	subs=("www" "lb-01" "web-01" "web-02")
	for sub in "${subs[@]}"; do
		dig_url "$1" "$sub"
	done
)
