#!/usr/bin/env bash
# a Bash script that will display information about subdomains

get_info () {
    record_type=$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline; print $4}')
    destination=$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline; print $5}')

    echo "The subdomain $2 is a $record_type record and points to $destination"
}


if [ "$#" -eq 1 ]; then
    subs=("www" "lb-01" "web-01" "web-02")
    for sub in "${subs[@]}"; do
        get_info "$1" "$sub"
    done
elif [ "$#" -eq 2 ]; then
    get_info "$1" "$2"
fi
