#!/usr/bin/env bash
# copies a file from client to server

file="$1"
addr="$2"
usr="$3"
idfile="$4"

if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi

echo "    PasswordAuthentication no" >> ~/.ssh/ssh_config
scp -i "$idfile" -o StrictHostKeyChecking=no "$file" "$usr@$addr:~"
