#!/usr/bin/env bash
# sets up nginx on a server and changes the default html

apt-get update
apt-get install nginx -y
ufw allow 80
echo "Hello" > /var/www/html/index*.html

echo 'server {
    listen 80;
    listen [::]:80;

    location /{
        return 200 "Hello World!\n";
}
}' | sudo cat > /etc/nginx/sites-available/default
service nginx restart
