#!/usr/bin/env bash
# sets up nginx on a server and changes the default html

apt-get update
apt-get install nginx -y
ufw allow 80
echo "Hello World!" > /var/www/html/index*.html
service nginx restart
