#!/usr/bin/env bash
# a script for creating 301 redirection

apt-get update
apt-get install nginx -y
ufw allow 80;
echo 'server {
	listen 80;
	listen [::]:80;

	server_name _;
	
	location / {
		return 200 "Hello World!\n";
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}' | cat > /etc/nginx/sites-available/default
service nginx restart
