#!/usr/bin/env bash
# a script for creating 301 redirection

apt-get update
apt-get install nginx -y
ufw allow 80;
echo "Hello World!" > index.html
mv index.html /var/www/html/
line="\tlocation \/redirect_me {\n\t\treturn 301 \$scheme:\/\/https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed  "/server_name _;/a\\$line" /etc/nginx/sites-available/default
sudo service nginx restart
