#!/usr/bin/env bash
# a script for creating 301 redirection

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 80;

echo "Hello World!" | sudo tee /var/www/index*.html
REDIRECT="\
	location /redirect {\n\
		return 301 https://www.google.com/;\n\
	}\n"

sudo sed -i "/server_name _;/a\ $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart 
