#!/usr/bin/env bash
# custom 404

apt-get update
apt-get install nginx
ufw allow 80;

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '0,/server_name _;/s//server_name _;\
	error_page 404 \/404.html;/g' /etc/nginx/sites-available/default
service nginx restart
