#!/usr/bin/env bash
# A program that tries to print Best School 10 times but just can't help itself
#+ and print Hi on the 9th line

i=0

while (( i<10 ))
do	
	echo "Best School"

	if (( i==8 ))
	then
		echo "Hi"
	fi
	(( i++ ))
done
		
