#!/usr/bin/env bash
# This is a script that prints some stuffs to screen

i=1

while ((i <= 20))
do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	(( i++ ))
done
