#!/usr/bin/env bash
# tries to solve task 1

cp /etc/hosts ~/hosts.new
sed -i '0,/[0-9]\slocalhost/{s/.*localhost/127.0.0.2		localhost/}' ~/hosts.new
facebook="8.8.8.8 	facebook.com"
echo "$facebook" >> ~/hosts.new
cp /etc/hosts ~/hosts.bck
cp -f ~/hosts.new /etc/hosts
