#!/usr/bin/env bash
# tries to solve task 1

sed '0,/127.0.0.1/{s/127.0.0.1/127.0.0.2/}' > /etc/hosts ~/hosts.new
facebook="8.8.8.8 	facebook.com"
echo "$facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
